### ISSUE TITLE
Borked leaderboard

### ISSUE THREAD

**Issue by ChirpyMisha** [MatrikMoon/TournamentAssistant#23]
The leaderboard on the left side doesn't show anyone. The Beat Saber 1.13.4 version of TournamentAssistant still shows the leaderboard correctly.

**Comment by MatrikMoon** [comment]
Thanks for submitting an issue! TA has not been updated for the latest version of beat saber yet, so I would recommend not using it until it is. Feel free to bug me on discord to update it :P

**Comment by ChirpyMisha** [comment]
Ah I see. Thank you for letting me know! ❤
For the 115 Royale tournament we have 2 weeks to play the qualifiers. The mod seems to be working and score submissions also work, so it's not too much of a problem that the leaderboard isn't working. But I (and many other people) would still greatly appreciate it if you could update the mod 🥰

**Comment by MatrikMoon** [comment]
I see... Please do bug me on discord then! :P
