### ISSUE TITLE
Question about overlay functionality

### ISSUE THREAD

**Issue by Phasfeldt** [MatrikMoon/TournamentAssistant#25]
I see that in the config, there's a port-configuration for some sort of overlay.

Am I correct to assume this is bound to be shown in OBS, as a browsersource, with IP:PORT? If that is the case, how is this set up correctly. I get met with a "System.IndexOutOfRangeException: Index was outside the bounds of the array.  At TournamentAssistantShared.Sockets.WsServer.AcceptCallback(IAsyncResult ar)" trying to use it.

Sorry if this has been answered on BSWC-Discord or other places, but I have not been able to find any answer for this.

Kind regards.

**Comment by Arimodu** [comment]
Hi, The overlay server just exposes the server calls to a websocket, you still need a webclient application acting as the overlay. 

As for your question, set-up is just setting a port in the config file to a different port than your server port (say server port is 10156 so your overlay port could be 10157)

If you have any more questions, or need help with the setup, you can get in touch with me or moon on discord.

**Comment by Phasfeldt** [comment]
> Hi, The overlay server just exposes the server calls to a websocket, you still need a webclient application acting as the overlay.
> 
> As for your question, set-up is just setting a port in the config file to a different port than your server port (say server port is 10156 so your overlay port could be 10157)
> 
> If you have any more questions, or need help with the setup, you can get in touch with me or moon on discord.

That answers my problems then, thank you @Arimodu :)
