### ISSUE TITLE
[Enhancement] Player acc in BotDatabase??

### ISSUE THREAD

**Issue by GrasshopperRU** [MatrikMoon/TournamentAssistant#33]
Would it be possible to have player acc, on the played map, added to the BotDatabase for qualifierscores submitted?

**Comment by MatrikMoon** [comment]
Hmm... I believe so, however keep in mind it's only possible to run qualifiers on the Master server at the moment, so unfortunately I'm not sure if you'd be able to make use of the added information. Feel free to reach out to me on discord if you want to talk more about it @moon#0002

**Comment by MatrikMoon** [comment]
Going ahead and closing this as I haven't heard back from you, and also I don't see the use for it personally.

I'm still available to be convinced if you make your case! But in the interest of closing inactive issues, I will now close this.
