### ISSUE TITLE
TournamentAssistantCore.exe Immediately Crashes upon Opening

### ISSUE THREAD

**Issue by speedymlg** [MatrikMoon/TournamentAssistant#38]
Theres not really much info into it, All of the files that i got from the release tab excluding the source code is in the same folder.

**Comment by speedymlg** [comment]
whoops.

**Comment by MatrikMoon** [comment]
Did you still need help?

**Comment by speedymlg** [comment]
fortunately no longer, the issue was that my C:\ drive was on around 30mb left, and tournament assistant require more to unpack

**Comment by MatrikMoon** [comment]
Ah! Yes, that's correct xD
I recommend SpaceSniffer if you're looking to free up more space! I use it all the time 😄
