### ISSUE TITLE
No password input field in game

### ISSUE THREAD

**Issue by OnSive** [MatrikMoon/TournamentAssistant#54]
I've set up my server with a password to keep the server clear while in tournament, but I couldn't find a way to enter the password ingame.

Is it somewhere hidden or just missing?

**Comment by Arimodu** [comment]
Just missing I believe. I spoke with Moon about it a bit ago so unless something has changed since that time then it's just missing.

**Comment by MatrikMoon** [comment]
Indeed, there's currently no way to enter the password on the client side. This is an issue that certainly needs to be fixed on my end. I'll leave this issue open until it's fixed, whether that's by adding a keyboard to type in the password or moving to other authentication methods. Thanks for the poke!

**Comment by MatrikMoon** [comment]
Just added this! Enjoy!
