### ISSUE TITLE
Invalid wire-type error when connecting to server with TournamentAssistantUI

### ISSUE THREAD

**Issue by MindLaborDev** [MatrikMoon/TournamentAssistant#56]
I get this error whenever I try to connect to a server with TournamentAssistantUI 0.6.7. I tested it with `magnesium.velvet.moe:2052` and `localhost:2052`. Both throw the same error whenever I try to connect. I can join the server with the TA mod in-game though. A WebSocket connection to port 2053 with node also works without issues.

![image](https://user-images.githubusercontent.com/42311986/200190203-066e725f-970f-4c57-b339-809f08261038.png)

**Comment by MatrikMoon** [comment]
Howdy! Reach out to me on discord for a little debugging, perhaps? Usually this is a version mismatch, but if it's not it's definitely worth tracking down

**Comment by MindLaborDev** [comment]
Whats your discord though?

**Comment by MatrikMoon** [comment]
For other readers: it seems the TAUI that was used was either corrupted or out of date. Grabbing a fresh copy did the trick! 😄
