### ISSUE TITLE
Bot leaderboard failing to edit/update

### ISSUE THREAD

**Issue by 16ajans** [MatrikMoon/TournamentAssistant#68]
Bot sends the leaderboard correctly *once,* but refuses to update it while correctly logging newly received scores to the channel.

![image](https://user-images.githubusercontent.com/20099946/223903555-883847c9-e85b-43e2-8a26-aca60ae9b41d.png)

Note the non-inclusion of the new scores in the leaderboard message.

Logged:
```
Mar 08 18:47:16 cvre01 TournamentAssistantCore[499911]: Object reference not set to an instance of an object.
Mar 08 18:47:16 cvre01 TournamentAssistantCore[499911]:    at TournamentAssistantCore.Discord.QualifierBot.SendLeaderboardUpdate(UInt64 channelId, UInt64 messageId, List`1 scores, List`1 maps)
Mar 08 18:47:16 cvre01 TournamentAssistantCore[499911]:    at TournamentAssistantCore.SystemServer.Server_PacketReceived(ConnectedUser user, Packet packet)
Mar 08 18:47:16 cvre01 TournamentAssistantCore[499911]:    at TournamentAssistantCore.Sockets.Server.ReceiveLoop(ConnectedUser player)
```

**Comment by MatrikMoon** [comment]
Thanks for logging the issue! The bot might not stick around for too much longer, but it'd be nice to have it working while it's here. This is a feature I've "fixed" countless times, and yet it always seems to get angry for one reason or another... If you're willing to test with me though, I'd be glad to give it another touchup ❤️

**Comment by MatrikMoon** [comment]
To the others who might read this: we did some testing, and came to the conclusion that the bot needs the Message Content privileged intent to edit the old message. Not much I can do about that from my side except maybe handle the error better, but for now, I'm going to close this since the bot is probably going away soon 🖖
