### ISSUE TITLE
Support for 1.36.2

### ISSUE THREAD

**Issue by tompointexe** [MatrikMoon/TournamentAssistant#73]
Hi, i wanted to know if there is planned support for more recent version of BeatSaber ?
Thanks

**Comment by raineio** [comment]
Moon has been making builds for newer versions of Beat Saber on request. But AFAIK, there is no present plan to do so before the rewrite of TA is completed.

**Comment by tompointexe** [comment]
Good to know that there is a rewrite in progress 👍 
Is there anyway a build for 1.36.2 (or even 1.37 when modding support comes) could be done, or it would be too much edits for it to work ?

**Comment by MatrikMoon** [comment]
Hyullo! Dang raine I didn't even have a chance to get off the phone before you responded 😆

Yup! Raine's right on all accounts, the rewrite has 1.36 support, but while it's relatively stable for Qualifiers, match support is currently unfinished and untested.

I don't currently plan to bring the stable 0.7.8 to 1.36, but if you have a particular need for some feature on a new BS version, we can probably work something out!

What are you aiming to do? Or if you'd prefer to talk on discord, you can hit me up @matrikmoon

**Comment by tompointexe** [comment]
Hey, just sent you a request on discord :)
will be easyer, i'l keep the issue updated later :)
